import type { InvitationTemplate } from "@/types";

export const TEMPLATES: InvitationTemplate[] = [
  {
    templateId: "garden-rose",
    name: "Garden Rose",
    category: "floral",
    description: "A soft, romantic design with blush pink tones and delicate floral motifs. Perfect for intimate garden weddings.",
    tags: ["romantic", "soft", "feminine", "roses"],
    region: "Pan-India",
    isPremium: false,
    bg: "linear-gradient(160deg, #fff1f2 0%, #ffe4e6 45%, #fecdd3 100%)",
    textColor: "text-rose-900",
    accentColor: "#e11d48",
    borderColor: "#fda4af",
    ornamentStyle: "floral",
  },
  {
    templateId: "sacred-mandala",
    name: "Sacred Mandala",
    category: "traditional",
    description: "Deep indigo meets gold in a divine design inspired by traditional Indian mandala art. Timeless and spiritual.",
    tags: ["mandala", "traditional", "spiritual", "divine"],
    region: "Pan-India",
    isPremium: false,
    bg: "linear-gradient(160deg, #1e1b4b 0%, #312e81 50%, #1e1b4b 100%)",
    textColor: "text-amber-200",
    accentColor: "#fbbf24",
    borderColor: "#f59e0b",
    ornamentStyle: "mandala",
  },
  {
    templateId: "mumbai-minimal",
    name: "Mumbai Minimal",
    category: "modern",
    description: "Clean lines and bold typography define this contemporary design. Ideal for the modern urban couple.",
    tags: ["minimal", "modern", "clean", "urban"],
    region: "Pan-India",
    isPremium: false,
    bg: "linear-gradient(160deg, #ffffff 0%, #fff5f5 100%)",
    textColor: "text-slate-900",
    accentColor: "#f43f5e",
    borderColor: "#fda4af",
    ornamentStyle: "minimal",
  },
  {
    templateId: "mughal-arch",
    name: "Mughal Arch",
    category: "royal",
    description: "Inspired by Mughal architecture — rich maroon, ornate arches, and gold calligraphy evoke regal grandeur.",
    tags: ["royal", "mughal", "grand", "opulent"],
    region: "North India",
    isPremium: true,
    bg: "linear-gradient(160deg, #7c2d12 0%, #991b1b 40%, #7c2d12 100%)",
    textColor: "text-amber-200",
    accentColor: "#fbbf24",
    borderColor: "#d97706",
    ornamentStyle: "arch",
  },
  {
    templateId: "tropical-garden",
    name: "Tropical Garden",
    category: "floral",
    description: "Lush emerald greens and tropical botanicals for couples who love nature and an outdoor celebration.",
    tags: ["tropical", "nature", "green", "outdoor"],
    region: "South India",
    isPremium: false,
    bg: "linear-gradient(160deg, #ecfdf5 0%, #d1fae5 50%, #a7f3d0 100%)",
    textColor: "text-emerald-900",
    accentColor: "#059669",
    borderColor: "#34d399",
    ornamentStyle: "leaves",
  },
  {
    templateId: "rajwada-palace",
    name: "Rajwada Palace",
    category: "royal",
    description: "Born from the grandeur of Rajasthani palaces — saffron, gold, and majestic ornaments fit for royalty.",
    tags: ["rajasthani", "palace", "saffron", "heritage"],
    region: "Rajasthan",
    isPremium: true,
    bg: "linear-gradient(160deg, #78350f 0%, #b45309 40%, #78350f 100%)",
    textColor: "text-amber-100",
    accentColor: "#fcd34d",
    borderColor: "#fbbf24",
    ornamentStyle: "geometric",
  },
  {
    templateId: "vintage-ivory",
    name: "Vintage Ivory",
    category: "floral",
    description: "Warm ivory tones with botanical illustrations and antique charm. Elegance that transcends trends.",
    tags: ["vintage", "ivory", "botanical", "classic"],
    region: "Pan-India",
    isPremium: true,
    bg: "linear-gradient(160deg, #fefce8 0%, #fef9c3 40%, #fef3c7 100%)",
    textColor: "text-stone-800",
    accentColor: "#92400e",
    borderColor: "#d97706",
    ornamentStyle: "botanical",
  },
  {
    templateId: "midnight-glamour",
    name: "Midnight Glamour",
    category: "modern",
    description: "Dark navy and liquid gold come together in a luxe, sophisticated design for the boldly fashionable couple.",
    tags: ["luxury", "dark", "glamour", "navy", "gold"],
    region: "Pan-India",
    isPremium: true,
    bg: "linear-gradient(160deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)",
    textColor: "text-amber-300",
    accentColor: "#f59e0b",
    borderColor: "#d97706",
    ornamentStyle: "stars",
  },
];

export function getTemplate(templateId: string): InvitationTemplate | undefined {
  return TEMPLATES.find((t) => t.templateId === templateId);
}

export const TEMPLATE_CATEGORIES = [
  { value: "all", label: "All" },
  { value: "traditional", label: "Traditional" },
  { value: "floral", label: "Floral" },
  { value: "royal", label: "Royal" },
  { value: "modern", label: "Modern" },
  { value: "festive", label: "Festive" },
] as const;
